---
title: "Lab 5 Computational Statistics"
author: "Omkar Bhutra (omkbh878),Andreas C Charitos(andch552)"
date: "27 February 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, message=FALSE, warning=FALSE, echo=FALSE,include=FALSE}
library("boot")
library("ggplot2")
```

```{r 1.1, message=FALSE, warning=FALSE, echo=FALSE}
lottery <- read.csv("lottery.csv", sep=";")
ggplot(lottery, aes(x=Day_of_year, y = Draft_No)) + geom_point() +
ggtitle("Draft Number vs. Day of birth")+labs(x="Birthday",y="Draft number")
```

```{r 1.2, message=FALSE, warning=FALSE, echo=FALSE}
ggplot(lottery, aes(x=Day_of_year, y = Draft_No)) +
geom_point() +
geom_smooth(method = loess) +
ggtitle("Draft Number vs. Day of birth")+labs(x="Birthday",y="Draft number")

model <- loess(Draft_No ~ Day_of_year, lottery)
lottery$Y_hat <- predict(model, lottery)
ggplot(lottery, aes(x=Day_of_year, y = Draft_No)) +
geom_point() +
geom_line(aes(y = Y_hat)) +
ggtitle("Draft Number vs. Day of birth without loess smoothening")+labs(x="Birthday",y="Draft number")
```

```{r 1.3, message=FALSE, warning=FALSE, echo=FALSE}
stat1 <- function(data, index){
data <- data[index,]
model <- loess(Draft_No ~ Day_of_year, data)
res <- predict(model, data)
X_a <- data$Day_of_year[which.max(data$Draft_No)]
X_b <- data$Day_of_year[which.min(data$Draft_No)]
Y_a <- res[X_a]
Y_b <-res[X_b]
answer <- ((Y_b - Y_a) / (X_b - X_a))
return(answer)
}

res <- boot(data=lottery, statistic = stat1, R=2000)
print(boot.ci(res)) 

plot(res)
```

```{r 1.4, message=FALSE, warning=FALSE, echo=FALSE}
my_permu <- function(data, index){
data <- data[index,]
model <- loess(Draft_No ~., data)
res <- predict(model, data)
X_a <- data$Day_of_year[which.max(data$Draft_No)]
X_b <- data$Day_of_year[which.min(data$Draft_No)]
Y_a <- res[X_a]
Y_b <-res[X_b]
answer <- ((Y_b - Y_a) / (X_b - X_a))
return(answer)
}
data <- lottery
data$Month <- NULL
res <- boot(data=lottery, statistic = stat1, R=2000)
plot(res)
```

### Apendix
```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```